services:
  app:
    build: .  # Dockerfile'ın bulunduğu dizin
    ports:
      - "8000:8000"  # Uygulama port yönlendirmesi
    depends_on:
      - db  # Veritabanına bağımlılık

  db:
    image: mysql:8.0  # MySQL 8.0 imajı
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: barber_appointment
    ports:
      - "3306:3306"  # Veritabanı port yönlendirmesi
